version: '3'

services:
  elroi-consumer-db:
    image: mysql:8.0
    container_name: elroi-consumer-db
    hostname: elori-db-host
    restart: always
    environment:
      MYSQL_DATABASE: 'elroi'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'elroi_consumer'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'secret'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - elroiConsumerApiNetwork
  elroi-consumer-api:
    container_name: elroi-consumer-api
    hostname: elroi-consumer-api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      elroi-consumer-db:
        condition: service_healthy
    networks:
      - elroiConsumerApiNetwork
  

volumes:
  mysql-data:

networks:
  elroiConsumerApiNetwork: {}
